---
tournaments:
  - name: "Fly to EMEA #3"
    url: "https://www.aesopstables.net/464"
  - name: "NANPC Boston"
    url: "https://www.aesopstables.net/470"
  - name: "ACC"
    url: "https://www.aesopstables.net/475"
  - name: "OTG Midwest"
    url: "https://www.aesopstables.net/483"
  - name: "APAC"
    url: "https://www.aesopstables.net/489"
  - name: "West Canadian Nats"
    url: "https://www.aesopstables.net/494"
  - name: "EMEA"
    url: "https://tournaments.nullsignal.games/tournaments/3466"
  - name: "ICC"
    url: "https://tournaments.nullsignal.games/tournaments/3487"
  - name: "NANPC Philadelphia"
    url: "https://www.aesopstables.net/550"
  - name: "East Canadian Nats"
    url: "https://tournaments.nullsignal.games/tournaments/3500"
  - name: "North Australian Nats"
    url: "https://www.aesopstables.net/558"
  - name: "UK Regionals Bristol"
    url: "https://www.aesopstables.net/565"
  - name: "Swedish Nats"
    url: "https://www.aesopstables.net/568"
  - name: "US East Coast Nats"
    url: "https://www.aesopstables.net/572"
  - name: "US West Coast Nats"
    url: "https://www.aesopstables.net/579"
  - name: "UK Regionals Nottingham"
    url: "https://www.aesopstables.net/582"
  - name: "German Nats"
    url: "https://tournaments.nullsignal.games/tournaments/3520"
  - name: "UK Regionals Aldershot"
    url: "https://tournaments.nullsignal.games/tournaments/3528"
  - name: "Swiss Nats"
    url: "https://www.aesopstables.net/604"
  - name: "French Nats"
    url: "https://www.aesopstables.net/607"
