- date: 2024-05-25
  location: online
  meta: '24.05'
  name: 'Fly to EMEA #3'
  url: https://www.aesopstables.net/464
- date: 2024-05-25
  meta: '24.05'
  name: NANPC Boston
  region: America
  url: https://www.aesopstables.net/470
- date: 2024-06-01
  location: online
  meta: '24.05'
  name: America Continental Championship 2024
  region: America
  url: https://www.aesopstables.net/475
- date: 2024-06-08
  meta: '24.05'
  name: OTG Midwest
  players:
    dongyroge: 40924
  region: America
  url: https://www.aesopstables.net/483
- date: 2024-06-15
  location: online
  meta: '24.05'
  name: APAC Continental Championship 2024
  region: APAC
  url: https://www.aesopstables.net/489
- date: 2024-06-15
  meta: '24.05'
  name: West Canadian Nats
  region: America
  url: https://www.aesopstables.net/494
- date: 2024-06-28
  meta: '24.05'
  name: EMEA Continental Championship 2024
  players:
    'Bridgeman ': 23764
  region: EMEA
  url: https://tournaments.nullsignal.games/tournaments/3466
- date: 2024-07-13
  location: online
  meta: '24.05'
  name: ICC
  url: https://tournaments.nullsignal.games/tournaments/3487
- date: 2024-07-13
  meta: '24.05'
  name: NANPC Philadelphia
  region: America
  url: https://www.aesopstables.net/550
- date: 2024-07-20
  meta: '24.05'
  name: East Canadian Nats
  players:
    Brandon: 31796
  region: America
  url: https://tournaments.nullsignal.games/tournaments/3500
- date: 2024-07-20
  meta: '24.05'
  name: North Australian Nats
  region: APAC
  url: https://www.aesopstables.net/558
- date: 2024-07-27
  meta: '24.05'
  name: UK Regionals Bristol
  region: EMEA
  url: https://www.aesopstables.net/565
- date: 2024-07-27
  location: online
  meta: '24.05'
  name: AMT - July 27th
  url: https://www.aesopstables.net/571
- date: 2024-07-27
  meta: '24.05'
  name: US East Coast Nats
  region: America
  url: https://www.aesopstables.net/572
- date: 2024-07-27
  meta: '24.05'
  name: Swedish Nats
  region: EMEA
  url: https://www.aesopstables.net/568
- date: 2024-08-03
  meta: '24.05'
  name: US West Coast Nats
  region: America
  url: https://www.aesopstables.net/579
- date: 2024-08-09
  meta: '24.05'
  name: German Nats
  region: EMEA
  url: https://tournaments.nullsignal.games/tournaments/3520
- date: 2024-08-10
  meta: '24.05'
  name: Russian Nats
  region: EMEA
  url: https://www.aesopstables.net/587
- date: 2024-08-10
  meta: '24.05'
  name: UK Regionals Nottingham
  region: EMEA
  url: https://www.aesopstables.net/582
- date: 2024-08-11
  location: online
  meta: '24.05'
  name: AMT - Aug 11th
  url: https://www.aesopstables.net/590
- date: 2024-08-23
  meta: '24.05'
  name: Swiss Nats
  region: EMEA
  url: https://www.aesopstables.net/604
- date: 2024-08-24
  location: online
  meta: '24.05'
  name: AMT - Aug 24th
  url: https://www.aesopstables.net/606
- date: 2024-08-24
  meta: '24.05'
  name: UK Regionals Aldershot
  region: EMEA
  url: https://tournaments.nullsignal.games/tournaments/3528
- date: 2024-08-24
  meta: '24.05'
  name: French Nats
  region: EMEA
  url: https://www.aesopstables.net/607
- date: 2024-08-24
  meta: '24.05'
  name: "NANPC Montr\xE9al"
  region: America
  url: https://www.aesopstables.net/608
- date: 2024-09-07
  meta: '24.05'
  name: UK Regionals Scotland
  region: EMEA
  url: https://tournaments.nullsignal.games/tournaments/3539
- date: 2024-09-07
  meta: '24.05'
  name: NANPC LA
  region: America
  url: https://www.aesopstables.net/687